### ISSUE TITLE
ブログ記事の画像がはみでる

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/front#134]
`img{width: 100%;}`で回避できそう なんではみでてるの…?

**Comment by ibuki2003** [comment]
他の画像についても同様に`width:100%`しちゃっていいかな? (反例(?)があるなら知りたい)

**Comment by ibuki2003** [comment]
PCは60% スマホは100%

- それより小さかったときの表示(拡大orそのまま)
  - 極端に小さいときに困る(下のblock要素にする問題と関連)
- block要素にしてよいかどうか(inline要素である必要性)
  - 60%だと中央揃えしないとかっこわるい)

の2点で要検討

**Comment by su8ru** [comment]
そっ閉じ
a31653b および #169
