### ISSUE TITLE
画像がでかい(instagram アイコン とか)

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/front#176]
> サイズ 172KB
> 減らせるデータ量 171KB

ロゴもでかいと言われてる

svgにできるところはする、 *次世代フォーマットでの画像の配信* をする

**Comment by su8ru** [comment]
次世代の先を行く *Fontawesome* はどうでしょう
Twitterとかは普通にそっちでいいよね

**Comment by ibuki2003** [comment]
次世代の先では、ないやろ
いいとおもいます
