### ISSUE TITLE
ページ遷移時にスクロールが保持される

### ISSUE THREAD

**Issue by su8ru** [afes-website/front#30]
Routerの設定を変えないといけないらしい

**Comment by su8ru** [comment]
> Links with href="#"
Typically `<a href="#">` will cause the document to scroll to the top of page when clicked. `<b-link>` addresses this by preventing the default action (scroll to top) when href is set to #.
If you need scroll to top behaviour, use a standard `<a href="#">...</a>` tag.
([Bootstrap Vue Reference](https://bootstrap-vue.js.org/docs/components/link/))

とのことなんですが…

**Comment by ibuki2003** [comment]
その挙動をみたことは多分なくて、ただ確かに問題はありそうですね router-linkのラッバー書いちゃうか
とりあえず別issueにするべきそう

**Comment by ibuki2003** [comment]
[スクロールの振る舞い | Vue Router](https://router.vuejs.org/ja/guide/advanced/scroll-behavior.html#%E9%9D%9E%E5%90%8C%E6%9C%9F%E3%81%AA%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%B0) にあるようにRouterに`scrollBehavior`をつけてあげればよさそう
