### ISSUE TITLE
スマホでヘッダが表示されない

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/front#364]
## 発現確認済みリスト

OS / 機種 / ブラウザ / vw

- iOS 13 / iPhone 8 / Safari / 375px
- iOS **??** / iPhone 10 / Safari / 375px

## 正常確認済みリスト

- iOS 14 / iPhone 12 / Safari / 390px
- iPadOS 14 / iPad Air 3 / Safari / ???px != 375px

## vw == 375px の端末リスト

- iPhone 10 @.3x
- iPhone 8 @.2x
- iPhone SE2 @.2x

---
以下初報

環境： iPhoneX, Safari

**Comment by su8ru** [comment]
Chrome Dev Tool および iPad 版 Safari / Chrome での再現を試みましたができませんでした。

**Comment by su8ru** [comment]
`App.vue:470-477`
```scss
  #left-wrapper {
    height: auto;
    padding: 0;
    // position: fixed // <- from pc

    header {
      display: block;
      height: auto;
      position: fixed; // <-
      top: 0;
```

のどっちかが原因なことまでは判明、`static` にすると正常表示されるが、他のブラウザだと当然乱れる

(急いで調べたので、どっちかまでは見れてない、多分後者)

`sticky` とかもだめ。どうしよう……………

**Comment by su8ru** [comment]
おそらく `#left-wrapper` の `position: fixed` が原因っぽい………？

直る気はするが、確証は持てない
