### ISSUE TITLE
お問い合わせフォームの作成

### ISSUE THREAD

**Issue by su8ru** [afes-website/front#40]
depends on afes-website/docs#11 (already closed)

学校のお問い合わせフォームにお問い合わせが行かないよう、文化祭ウェブサイトにお問い合わせフォームを実装する
afes.info -> GoogleForm -> [contact@afes.info, Slack#notify-contactform]

この辺参考に
- [Vue\.jsとGoogle フォームでお問い合わせフォームを手軽に作る（コピペ可） \- Qiita](https://qiita.com/ykoizumi0903/items/9a1bf871f477651817a8)
- [Googleフォームを自在にカスタマイズする \- Qiita](https://qiita.com/curioussafuta/items/fa077cbf820faca30598)
- [Googleフォームをカスタマイズして導入、Ajax処理を行う \- Qiita](https://qiita.com/sugitata/items/182173c01e0470a3a4a8#_reference-a3a8c18aab158ee0c9de)

**Comment by Takeno-hito** [comment]
進捗どうですか
