### ISSUE TITLE
LoginModal関連

### ISSUE THREAD

**Issue by su8ru** [afes-website/front#64]
- `z-index` を
  - PC: LoginModal > `.menu` = `.top`
  - mobile: `.menu` > `.top` > LoginModal

  にすべき

**Comment by ibuki2003** [comment]
opacityが死んでる件もついでに(これは`main.scss`にて`@import "~bootstrap-vue";`で解決することを確認済みですが

**Comment by ibuki2003** [comment]
> mobile: `.menu` > `.top` > LoginModal

これは本当ですか 上隠れるしヘッダが手前に来てもあまりうれしく感じない あと構造上めんどくさい

**Comment by su8ru** [comment]
わからん おまかせ
