### ISSUE TITLE
新型肺炎流行に伴う日程変更対応

### ISSUE THREAD

**Issue by su8ru** [afes-website/front#87]
2020.6.12-14 を予定
正式発表かわからないのでこれを記載していいのかわからん

**Comment by Takeno-hito** [comment]
えっと、6.12~14にした上で、変更の可能性あり、とかの文は全部消してほしいです。
あと、 https://afes.info/blog/news/covid19-announce を作ったのでこのリンクもトップページに「お知らせ」として貼ってほしいです

**Comment by Takeno-hito** [comment]
あとまだ作業してないなら、これはhotfixでだしてほしい、他のブログの作業目処がちょっと立ってない

**Comment by su8ru** [comment]
変更の可能性あり、消していいのか（まだ断定っぽさを感じた）

新型コロナウイルス感染症（COVID-19） が相応しいと思う

**Comment by Takeno-hito** [comment]
ごめんなさい、残して

**Comment by Takeno-hito** [comment]
えっと、文章に関しては既に文実であちこち貼ってるものを使ってます
https://twitter.com/73_Afes/status/1233905384324091905?s=20

**Comment by su8ru** [comment]
そのまま、嘘じゃん

Twitterタグはハイフンが使えない仕様なのでしょうがないけど、WHOはハイフン付きです
