### ISSUE TITLE
記事プレビューでno-imageだと寂しい

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/front#97]
記事プレビューで画像がなかった時に、麻布の校章なりAfesロゴがないと、見た目として寂しい

**Comment by ibuki2003** [comment]
記事内最初の画像をそこに表示でいいかな
画像ないときのフォールバックは要検討のためdiscussをつけます

**Comment by ibuki2003** [comment]
スマホ表示時に画像を非表示とかいう案があった気がするんでそれも検討

**Comment by su8ru** [comment]
- 寂しくない no-image を作ります
- スマホは非表示にします

どうでしょうか
